### ISSUE TITLE
Warn if a PR changes Cargo.lock

### ISSUE THREAD

**Issue by kennytm** [rust-lang/highfive#153]
In rust-lang/rust we will not automatically merge diff from Cargo.lock (see rust-lang/rust#46539 for rationale). This means all PRs modifying Cargo.lock are mutually exclusive with each other, and when one such PR is merged, all other PRs will need to be rebased. 

This may bother reviewers and authors when the PR needs to be rebased and r+'ed several times. It is also pretty confusing to new contributors because a rebase often completes without any conflicts locally.

Thus, I think it is the best for rust-highfive to foreshadow such potential extra work to both reviewers and authors.

> ### ⚠️ Warning ⚠️ 
>
> This PR modified **Cargo.lock**. We will not automatically merge updates to Cargo.lock, since it often leaves the file in a broken state. One unfortunate result is that this often leads to merge conflicts.
>
> You may need to rebase this PR several times after it has been approved. We are sorry for any inconvenience which may arise.
>
> *(Note to reviewers: Please also prepare to r+ several times. Consider giving it a p=1 to minimize queuing time and reduce chance of conflict.)*

**Comment by mati865** [comment]
Does this still apply today when Cargo.lock can be automatically merged?

**Comment by kennytm** [comment]
Right. 

Fixed by #63743.
