### ISSUE TITLE
Assign a random team member with r+ priviliges on r? @rust-lang/<team>

### ISSUE THREAD

**Issue by Centril** [rust-lang/highfive#187]
If someone writes:
```
r? @rust-lang/docs 
```
Then we could for example assign steveklabnik since they have r+ rights.

This mistake happens from time to time; what happens now when someone writes the above is to leave the PR without a reviewer...

cc https://github.com/rust-lang/rust/pull/57357#issuecomment-451675541

**Comment by pietroalbini** [comment]
I'm not sure if it's that useful to intersect with the list of users with r+ rights though. The list seems correct to me, cc @davidalber

**Comment by SimonSapin** [comment]
Would it be enough to stick to the default directory-based assignment algorithm? https://github.com/rust-lang/highfive/issues/241 could be an alternative if so.

> when someone writes the above is to leave the PR without a reviewer

That sounds like a bug in itself, highfive should never unassign without assigning someone else.
