### ISSUE TITLE
rust-highfive only warns about updated submodules when a PR is created

### ISSUE THREAD

**Issue by varkor** [rust-lang/highfive#223]
Or maybe it also warns when a new commit is pushed, but definitely not when commits are force pushed (as seen in https://github.com/rust-lang/rust/pull/62235).

**Comment by jyn514** [comment]
Looking at `app.py`, it seems like highfive *only* ever runs on new PRs, never changes. Someone will need to add the ability to look at changes to highfive (or more likely, rewrite the whole thing into triagebot).

**Comment by RalfJung** [comment]
The issue also applies to pinging teams when a PR touches code in their responsibility.

**Comment by ehuss** [comment]
I have opened a PR at https://github.com/rust-lang/triagebot/pull/1625 which aims to solve this issue (and moves "mentions" to triagebot).

**Comment by ehuss** [comment]
This should now essentially be fixed in triagebot, so I think this could probably be closed.
