### ISSUE TITLE
feature request: warn if src/test/ is modified without modifying compiler/ or src/librustdoc/

### ISSUE THREAD

**Issue by jyn514** [rust-lang/highfive#286]
This would help prevent an ever-growing backlog for https://github.com/rust-lang/rust/issues/76268.

**Comment by matklad** [comment]
I think are more precise rule would work like this:

* Warn if a PR modifies *only* `library/` and `src/test`. 


This actually should bring false-positive rate to almost zero I think.

**Comment by workingjubilee** [comment]
Would this be part of `x.py test tidy`, or something else?

**Comment by jyn514** [comment]
I don't think it should be part of tidy, because it could have false positives. `tidy` is a hard error, I want this to be more like submodules where it says 'only do this if you're sure'.

**Comment by Mark-Simulacrum** [comment]
It would probably be better as a request against triagebot, where most new functionality should go. We are already receiving the webhook needed for this so mostly a matter of hooking up a check for the rule @matklad laid out above. AFAIK, no checks on the diff of PRs exists in triagebot today so we'll probably need to add some logic for that.

**Comment by jyn514** [comment]
Opened https://github.com/rust-lang/triagebot/issues/831
