### ISSUE TITLE
Warn on change to targets

### ISSUE THREAD

**Issue by jhwgh1968** [rust-lang/highfive#310]
As a passer by, I notice the following has happened a couple of times in the last release-and-a-half on a PR for adding or modifying a compiler target:

* A reviewer didn't know if we had a policy, and a different one closer to the subject matter pointed them to [this RFC](https://github.com/rust-lang/rfcs/pull/2803).
* A reviewer didn't know we had a policy about tier 3 and just merged it (or so the comment chain implies).
* A reviewer forgot to tag release notes on a PR that added a tier 3 target.

This seems to me like an issue with consistency as the Rust team -- and reviewer pool for such issues -- grows. And what's the answer to those? A bot!

I thus propose an addition to Highfive similar to the "wrong branch" and "updates submodules" warnings. If certain files required to add a new target were in the PR diff, it would print this message:

> :warning: These commits add or update **compiler targets**. :warning: 
>
> Any target changes or additions should follow the [platform tiering policy](https://github.com/rust-lang/rfcs/pull/2803). Reviewers may ask for more information, especially if this target is above Tier 3.
>
> @ rustbot +relnotes

If this sounds good, I would even offer to implement it -- though it will probably be a while. :smile:

**Comment by joshtriplett** [comment]
That sounds like a great idea to me.
