### ISSUE TITLE
highfive should not assign someone to their own PR

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/highfive#326]
In https://github.com/rust-lang/rust/pull/84257 , rust-highfive assigned me to review my own PR.

**Comment by m-ou-se** [comment]
That's weird. It specifically excludes the author of the PR here:

https://github.com/rust-lang/highfive/blob/a2e3b19385e1cc6a665ca0c0e3226754856c59f9/highfive/newpr.py#L306

Which comes from the last argument here:

https://github.com/rust-lang/highfive/blob/a2e3b19385e1cc6a665ca0c0e3226754856c59f9/highfive/newpr.py#L384-L386

Set here:
https://github.com/rust-lang/highfive/blob/a2e3b19385e1cc6a665ca0c0e3226754856c59f9/highfive/newpr.py#L369

**Comment by m-ou-se** [comment]
Ah, the casing of your username in the high-five config doesn't match the one github uses: `JoshTriplett` vs  `joshtriplett`

https://github.com/rust-lang/highfive/blob/a2e3b19385e1cc6a665ca0c0e3226754856c59f9/highfive/configs/rust-lang/rust.json#L16

If you click `[edit]` on https://github.com/rust-lang/rust/pull/84257#issuecomment-821529104, you can see the bot is using `JoshTriplett` and not `joshtriplett` (even though github shows the former as the latter).

**Comment by joshtriplett** [comment]
@m-ou-se Ah, interesting. Ideally the bot should match ignoring case the same way GitHub does, but in the meantime, it sounds like the easiest fix would be to change my username in the configuration to all-lowercase.
