### ISSUE TITLE
no longer can assign specific users

### ISSUE THREAD

**Issue by ehuss** [rust-lang/highfive#380]
In https://github.com/rust-lang/cargo/pull/10313#issuecomment-1024600368, Alex attempted to do `r? @joshtriplett`, but it assigned `ehuss`.

Looking at https://github.com/rust-lang/highfive/blob/b54f0817ca2226a34adcf438c68758b8266bb13d/highfive/newpr.py#L250-L262 which changed in #377, it seems like it always picks from the `all` group, even if you specify a specific user.  @Mark-Simulacrum I can't quite understand what the intent of that change.  Is there a reason it always picks from `all`?

**Comment by Mark-Simulacrum** [comment]
Hm, no I don't understand why we're doing that. I think the picking from all was already present, just used to be only if you asked for a whole team, though?
