### ISSUE TITLE
Warn the user if they try to assign someone without review privileges

### ISSUE THREAD

**Issue by varkor** [rust-lang/highfive#85]
Currently, if you r? a user who doesn't have the right to r+, rust-highfive will silently ignore it. This can be a little confusing: it'd be nicer if there was some indication of what went wrong.

**Comment by lcnr** [comment]
Did this change or am I misinterpreting this issue :sweat_smile:  I've gotten assign to a PR without having the right to r+ in https://github.com/rust-lang/rust/pull/73254

**Comment by varkor** [comment]
Huh, it does seem to work now. I'll close unless there's any indication otherwise.
